// Worked examples for the process flow mapper. Each one is here to show one
// thing, named in `lesson`, with figures small enough to check by hand.

const lines = (...rows) => `${rows.join('\n')}\n`;

export const PRESETS = Object.freeze([
    {
        id: 'purchase',
        label: 'Purchase request',
        title: 'Purchase request',
        lesson: 'Look at Efficiency. The work is about an hour and the request takes over four days, nearly all of it waiting for a manager and for finance. Then look at Capacity: the manager, with a tenth of a week for approvals, is what limits how many requests this can carry.',
        text: lines(
            'lanes: Requester, Manager, Finance, Purchasing',
            'arrivals: 30 / wk',
            'staff: Requester 6 @ 10%, Manager 1 @ 10%, Finance 1 @ 25%, Purchasing 2 @ 50%',
            '',
            '== Request ==',
            'Requester: (Need identified) -> Fill in request',
            'Requester: Fill in request {15 min} -> Approve request?',
            'Manager: Approve request? {5 min, wait 2 d} -> yes 80%: Budget available?, no 5%: (Request declined), fix 15%: Fill in request',
            'Manager: (Request declined)',
            '',
            '== Funding ==',
            'Finance: Budget available? {10 min, wait 1 d} -> yes 90%: Raise purchase order, no 10%: (No budget)',
            'Finance: (No budget)',
            '',
            '== Order ==',
            'Purchasing: Raise purchase order {20 min, wait 4 h} -> Order correct?',
            'Purchasing: Order correct? {5 min} -> yes 92%: Send to supplier, no 8%: Raise purchase order',
            'Purchasing: Send to supplier {5 min, wait 2 h} -> (Order placed)',
            'Purchasing: (Order placed)'
        )
    },
    {
        id: 'lab',
        label: 'Lab sample with a retest loop',
        title: 'Lab sample, receipt to report',
        lesson: 'One result in five fails review and the sample is prepared and run again, so every step inside that loop is done 1.25 times (1 / 0.8). The badges show it, and "Rework adds" in the sentence above says what it costs.',
        text: lines(
            'lanes: Reception, Analyst, Reviewer',
            'arrivals: 40 / d',
            'staff: Reception 1, Analyst 8, Reviewer 2',
            '',
            '== Receive ==',
            'Reception: (Sample received) -> Log sample',
            'Reception: Log sample {5 min, wait 20 min} -> Prepare sample',
            '',
            '== Analyse ==',
            'Analyst: Prepare sample {20 min, wait 4 h} -> Run analysis',
            'Analyst: Run analysis {30 min, wait 1 h} -> Result valid?',
            'Reviewer: Result valid? {10 min, wait 2 h} -> yes 80%: Write report, no 20%: Prepare sample',
            '',
            '== Report ==',
            'Analyst: Write report {15 min, wait 30 min} -> Report approved?',
            'Reviewer: Report approved? {5 min, wait 1 h} -> yes 95%: (Report issued), no 5%: Write report',
            'Reviewer: (Report issued)'
        )
    },
    {
        id: 'change',
        label: 'Engineering change order',
        title: 'Engineering change order',
        lesson: 'A change the board sends back goes to drafting again, and drafting has its own checking loop. The loops multiply: drafting is done 1.9 times (1 / 0.75 x 1 / 0.7), not 1.3 or 1.4.',
        text: lines(
            'lanes: Requester, Engineer, Checker, Change board, Document control',
            '',
            '== Raise ==',
            'Requester: (Change requested) -> Assess impact',
            'Engineer: Assess impact {1 h, wait 1 d} -> Draft change',
            '',
            '== Draft ==',
            'Engineer: Draft change {2 h, wait 4 h} -> Check drawing',
            'Checker: Check drawing {30 min, wait 1 d} -> Drawing OK?',
            'Checker: Drawing OK? {5 min} -> yes 75%: Review change, no 25%: Draft change',
            '',
            '== Approve ==',
            'Change board: Review change {20 min, wait 3 d} -> Approved?',
            'Change board: Approved? {10 min} -> yes 70%: Release change, no 30%: Draft change',
            '',
            '== Release ==',
            'Document control: Release change {15 min, wait 4 h} -> Notify production',
            'Document control: Notify production {10 min} -> (Change released)',
            'Document control: (Change released)'
        )
    },
    {
        id: 'hiring',
        label: 'Hiring, application to offer',
        title: 'Hiring, application to offer',
        lesson: 'Look at "Where work ends up". Nothing is sent back here, so the question is not how long but where applications stop: three in four at the first screen, and two in a hundred at a hire. "Work per week" in the lane table shows what the rest cost the interview panel.',
        text: lines(
            'lanes: Candidate, Recruiter, Hiring manager, Interview panel',
            'arrivals: 60 / wk',
            '',
            '== Screen ==',
            'Candidate: (Application received) -> Screen application',
            'Recruiter: Screen application {6 min, wait 3 d} -> yes 25%: Phone screen, no 75%: (Declined at application)',
            'Recruiter: (Declined at application)',
            'Recruiter: Phone screen {30 min, wait 4 d} -> yes 50%: Technical interview, no 50%: (Declined after phone screen)',
            'Recruiter: (Declined after phone screen)',
            '',
            '== Interview ==',
            'Hiring manager: Technical interview {1 h, wait 1 wk} -> yes 40%: Panel interview, no 60%: (Declined after interview)',
            'Interview panel: Panel interview {3 h, wait 1 wk} -> yes 50%: Make offer, no 50%: (Declined after interview)',
            'Hiring manager: (Declined after interview)',
            '',
            '== Offer ==',
            'Recruiter: Make offer {45 min, wait 3 d} -> yes 80%: (Hired), no 20%: (Offer turned down)',
            'Recruiter: (Hired)',
            'Candidate: (Offer turned down)'
        )
    },
    {
        id: 'order',
        label: 'Order, pick to ship',
        title: 'Customer order, pick to ship',
        lesson: 'Picking is the longest job at 25 minutes. The darkest step is booking the carrier, a 4 minute job that waits a day. Set "Shade steps by" to Touch time to see the difference. The one order in ten that waits for stock costs more than picking does. Capacity names a different bottleneck: the warehouse, at 92% busy, is what limits how many orders can go through.',
        text: lines(
            'lanes: Sales, Warehouse, Shipping',
            'arrivals: 120 / d',
            'staff: Sales 2, Warehouse 11, Shipping 4',
            '',
            '== Order ==',
            'Sales: (Order received) -> Enter order',
            'Sales: Enter order {6 min, wait 30 min} -> In stock?',
            'Warehouse: In stock? {2 min, wait 10 min} -> yes 90%: Pick items, no 10%: Wait for stock',
            'Warehouse: Wait for stock {5 min, wait 3 d} -> Pick items',
            '',
            '== Fulfil ==',
            'Warehouse: Pick items {25 min, wait 1 h} -> Pack order',
            'Warehouse: Pack order {10 min, wait 20 min} -> Packed right?',
            'Warehouse: Packed right? {2 min} -> yes 97%: Book carrier, no 3%: Pick items',
            '',
            '== Ship ==',
            'Shipping: Book carrier {4 min, wait 1 d} -> Load truck',
            'Shipping: Load truck {8 min, wait 2 h} -> (Order shipped)',
            'Shipping: (Order shipped)'
        )
    },
    {
        id: 'incident',
        label: 'Incident response',
        title: 'Incident response',
        lesson: 'Look at "Check these". Escalating to the vendor leads nowhere on this map, so those incidents stop there and never close. "Where work ends up" says how many. The map draws the gap instead of hiding it.',
        text: lines(
            'lanes: Reporter, Service desk, Engineer',
            'arrivals: 25 / d',
            '',
            '== Log ==',
            'Reporter: (Incident reported) -> Log ticket',
            'Service desk: Log ticket {5 min, wait 10 min} -> Known issue?',
            'Service desk: Known issue? {5 min, wait 15 min} -> yes 40%: Apply known fix, no 60%: Investigate',
            '',
            '== Fix ==',
            'Service desk: Apply known fix {15 min} -> Fixed?',
            'Engineer: Investigate {1 h, wait 2 h} -> Fixed?',
            'Service desk: Fixed? {10 min} -> yes 85%: Confirm with reporter, no 10%: Investigate, stuck 5%: Escalate to vendor',
            'Engineer: Escalate to vendor {20 min}',
            '',
            '== Close ==',
            'Service desk: Confirm with reporter {5 min, wait 4 h} -> Still fixed?',
            'Reporter: Still fixed? {2 min} -> yes 92%: (Incident closed), no 8%: Investigate',
            'Reporter: (Incident closed)'
        )
    },
    {
        id: 'onboarding',
        label: 'New starter, three things at once',
        title: 'New starter, offer to first day',
        lesson: 'Once the record is open, checks, laptop and desk are all done at the same time (the arrow is =>). Lead time follows the slowest of the three, the checks. The laptop has nearly two days of slack and the desk more than four, so making either faster changes nothing. Touch time still counts all three. The SIPOC table under the lanes comes from the in: and out: lines.',
        text: lines(
            'lanes: Hiring manager, HR, IT, Facilities',
            '',
            '== Prepare ==',
            'in: Signed offer from New starter, Role details from Hiring manager',
            'out: Starter record to IT, Starter record to Facilities',
            'HR: (Offer accepted) -> Open starter record',
            'HR: Open starter record {20 min, wait 4 h} => Run checks, Order laptop, Book desk',
            '',
            '== Get ready ==',
            'in: References from Referees, Laptop from Supplier',
            'out: Cleared checks to Hiring manager, Laptop and account to New starter, Desk to New starter',
            'HR: Run checks {30 min, wait 5 d} -> Checks clear?',
            'HR: Checks clear? {10 min} -> yes 90%: Confirm start date, no 10%: Run checks',
            'IT: Order laptop {15 min, wait 3 d} -> Set up laptop and account',
            'IT: Set up laptop and account {1.5 h, wait 4 h} -> Confirm start date',
            'Facilities: Book desk {10 min, wait 1 d} -> Confirm start date',
            '',
            '== Start ==',
            'in: Cleared checks from HR',
            'out: Start date to New starter',
            'Hiring manager: Confirm start date {10 min, wait 2 h} -> (First day)',
            'Hiring manager: (First day)'
        )
    },
    {
        id: 'claim',
        label: 'Insurance claim, average against typical',
        title: 'Insurance claim, notice to payment',
        lesson: 'Look at "How long it takes" under the headline. Waits here are typed as ranges: "wait 1-2-6 d" is at least one day, usually two, at most six. The average is 12 days, but half of claims are done in under 11, and one in twenty takes more than four weeks: the ones that need a site visit, a chase for documents, or both. If you have to quote a time, quote the 8 in 10 figure, not the average.',
        text: lines(
            'lanes: Customer, Claims handler, Assessor, Finance',
            '',
            '== Notify ==',
            'Customer: (Claim made) -> Register claim',
            'Claims handler: Register claim {15 min, wait 2-4-24 h} -> Documents complete?',
            'Claims handler: Documents complete? {10 min} -> yes 70%: Assess claim, no 30% {1-3-10 d}: Chase documents',
            'Claims handler: Chase documents {10 min} -> Documents complete?',
            '',
            '== Assess ==',
            'Assessor: Assess claim {45 min, wait 1-2-6 d} -> small 60%: Approve payment?, large 40%: Visit site',
            'Assessor: Visit site {2 h, wait 3-5-15 d} -> Approve payment?',
            'Claims handler: Approve payment? {15 min, wait 2-8 h} -> yes 85%: Pay claim, no 15%: (Claim declined)',
            'Claims handler: (Claim declined)',
            '',
            '== Pay ==',
            'Finance: Pay claim {10 min, wait 1-3 d} -> (Claim paid)',
            'Finance: (Claim paid)'
        )
    }
]);

export const PRESETS_BY_ID = Object.freeze(Object.fromEntries(PRESETS.map((p) => [p.id, p])));
