import { getDocxTokenStyle } from "./token-styles.js";

const BLOCK_CONTAINER_TAGS = new Set(["DIV", "SECTION", "ARTICLE", "FIGURE"]);
const LIST_TAGS = new Set(["UL", "OL"]);
const DOCX_CODE_FONT = "Consolas";

export async function buildDocxBlob(docxLib, exportRoot, options) {
    const warnings = [];
    const context = { docxLib, warnings, inBlockquote: false };
    const children = await convertBlockNodes(Array.from(exportRoot.childNodes), context);
    const page = getPageSetup(docxLib, options);

    const document = new docxLib.Document({
        creator: "Jesse Anderson",
        title: options.title || options.filename || "Markdown Export",
        description: "Generated by Tools Hub Markdown Exporter",
        numbering: {
            config: buildNumberingConfig(docxLib)
        },
        sections: [
            {
                properties: {
                    page: {
                        margin: {
                            top: page.marginTwips,
                            right: page.marginTwips,
                            bottom: page.marginTwips,
                            left: page.marginTwips
                        },
                        size: {
                            width: page.widthTwips,
                            height: page.heightTwips,
                            orientation: page.orientation
                        }
                    }
                },
                children: children.length ? children : [new docxLib.Paragraph("")]
            }
        ]
    });

    return {
        blob: await docxLib.Packer.toBlob(document),
        warnings
    };
}

function buildNumberingConfig(docxLib) {
    return [
        {
            reference: "markdown-exporter-ordered",
            levels: [
                {
                    level: 0,
                    format: docxLib.LevelFormat.DECIMAL,
                    text: "%1.",
                    alignment: docxLib.AlignmentType.LEFT,
                    style: { paragraph: { indent: { left: 720, hanging: 360 } } }
                },
                {
                    level: 1,
                    format: docxLib.LevelFormat.LOWER_LETTER,
                    text: "%2.",
                    alignment: docxLib.AlignmentType.LEFT,
                    style: { paragraph: { indent: { left: 1440, hanging: 360 } } }
                },
                {
                    level: 2,
                    format: docxLib.LevelFormat.LOWER_ROMAN,
                    text: "%3.",
                    alignment: docxLib.AlignmentType.LEFT,
                    style: { paragraph: { indent: { left: 2160, hanging: 360 } } }
                },
                {
                    level: 3,
                    format: docxLib.LevelFormat.DECIMAL,
                    text: "%4.",
                    alignment: docxLib.AlignmentType.LEFT,
                    style: { paragraph: { indent: { left: 2880, hanging: 360 } } }
                }
            ]
        }
    ];
}

function getPageSetup(docxLib, options) {
    const widthIn = options.pageSize === "a4" ? 8.27 : 8.5;
    const heightIn = options.pageSize === "a4" ? 11.69 : 11;
    const landscape = options.orientation === "landscape";
    return {
        widthTwips: Math.round((landscape ? heightIn : widthIn) * 1440),
        heightTwips: Math.round((landscape ? widthIn : heightIn) * 1440),
        marginTwips: Math.round((options.marginIn || 0.5) * 1440),
        orientation: landscape ? docxLib.PageOrientation.LANDSCAPE : docxLib.PageOrientation.PORTRAIT
    };
}

async function convertBlockNodes(nodes, context) {
    const output = [];
    for (const node of nodes) {
        if (node.nodeType === Node.TEXT_NODE) {
            const text = normalizeText(node.textContent || "", false);
            if (text.trim()) {
                output.push(makeParagraph(context.docxLib, [new context.docxLib.TextRun(text)], {
                    spacing: { after: 180 }
                }));
            }
            continue;
        }
        if (node.nodeType !== Node.ELEMENT_NODE) continue;
        output.push(...(await convertBlockElement(node, context)));
    }
    return output;
}

async function convertBlockElement(element, context) {
    const tag = element.tagName.toUpperCase();
    switch (tag) {
        case "H1":
        case "H2":
        case "H3":
        case "H4":
        case "H5":
        case "H6":
            return [await convertHeading(element, tag, context)];
        case "P":
            return [await convertParagraph(element, context)];
        case "BLOCKQUOTE":
            return convertBlockquote(element, context);
        case "PRE":
            return convertCodeBlock(element, context);
        case "UL":
            return convertList(element, false, 0, context);
        case "OL":
            return convertList(element, true, 0, context);
        case "TABLE":
            return [await convertTable(element, context)];
        case "HR":
            return [new context.docxLib.Paragraph({ thematicBreak: true, spacing: { before: 300, after: 300 } })];
        case "IMG":
            return [await convertStandaloneImage(element, context)];
        default:
            if (BLOCK_CONTAINER_TAGS.has(tag)) {
                return convertBlockNodes(Array.from(element.childNodes), context);
            }
            return [await convertParagraph(element, context)];
    }
}

async function convertHeading(element, tag, context) {
    const docxLib = context.docxLib;
    const levelMap = {
        H1: docxLib.HeadingLevel.HEADING_1,
        H2: docxLib.HeadingLevel.HEADING_2,
        H3: docxLib.HeadingLevel.HEADING_3,
        H4: docxLib.HeadingLevel.HEADING_4,
        H5: docxLib.HeadingLevel.HEADING_5,
        H6: docxLib.HeadingLevel.HEADING_6
    };
    const spacingMap = {
        H1: { before: 0, after: 200 },
        H2: { before: 280, after: 140 },
        H3: { before: 240, after: 120 },
        H4: { before: 220, after: 100 },
        H5: { before: 200, after: 80 },
        H6: { before: 180, after: 80 }
    };

    const children = await extractInlineChildren(element, context, { preserveWhitespace: false });
    return makeParagraph(docxLib, children.length ? children : [new docxLib.TextRun("")], {
        heading: levelMap[tag],
        spacing: spacingMap[tag],
        keepNext: true
    });
}

async function convertParagraph(element, context) {
    const children = await extractInlineChildren(element, context, { preserveWhitespace: false });
    return makeParagraph(
        context.docxLib,
        children.length ? children : [new context.docxLib.TextRun("")],
        paragraphStyleForContext(context)
    );
}

async function convertBlockquote(element, context) {
    const groupedContent = groupContentNodes(Array.from(element.childNodes));
    if (!groupedContent.length) {
        return [await convertParagraph(element, { ...context, inBlockquote: true })];
    }

    const output = [];
    for (const group of groupedContent) {
        if (group.type === "inline") {
            if (!inlineNodesHaveVisibleContent(group.nodes)) {
                continue;
            }
            const runs = await extractInlineChildrenFromNodes(group.nodes, context, { preserveWhitespace: false });
            if (runs.length) {
                output.push(makeParagraph(context.docxLib, runs, paragraphStyleForContext({ ...context, inBlockquote: true })));
            }
            continue;
        }
        output.push(...(await convertBlockElement(group.element, { ...context, inBlockquote: true })));
    }
    return output;
}

function convertCodeBlock(element, context) {
    const docxLib = context.docxLib;
    const codeElement = element.querySelector("code") || element;
    const lines = trimTrailingBlankCodeLines(extractCodeLines(Array.from(codeElement.childNodes)));
    const borderEdge = { color: "1E293B", size: 8, style: docxLib.BorderStyle.SINGLE };

    return lines.map((line, index) => new docxLib.Paragraph({
        children: buildCodeLineRuns(docxLib, line),
        spacing: {
            before: index === 0 ? 120 : 0,
            after: index === lines.length - 1 ? 200 : 0
        },
        indent: { left: 120, right: 120 },
        border: {
            top: index === 0 ? borderEdge : undefined,
            bottom: index === lines.length - 1 ? borderEdge : undefined,
            left: borderEdge,
            right: borderEdge
        },
        shading: { type: docxLib.ShadingType.CLEAR, fill: "0B1220", color: "auto" }
    }));
}

async function convertList(listElement, ordered, depth, context) {
    const docxLib = context.docxLib;
    const paragraphs = [];

    for (const item of Array.from(listElement.children)) {
        if (item.tagName.toUpperCase() !== "LI") continue;

        const nestedLists = [];
        const contentNodes = [];
        Array.from(item.childNodes).forEach((node) => {
            if (isListElement(node)) {
                nestedLists.push(node);
            } else {
                contentNodes.push(node);
            }
        });

        const groupedContent = groupContentNodes(contentNodes);
        let assignedListMarker = false;

        for (const group of groupedContent) {
            if (group.type === "inline") {
                if (!inlineNodesHaveVisibleContent(group.nodes)) {
                    continue;
                }
                const runs = await extractInlineChildrenFromNodes(group.nodes, context, { preserveWhitespace: false });
                if (!runs.length && assignedListMarker) {
                    continue;
                }
                paragraphs.push(makeListParagraph(docxLib, runs, ordered, depth, context));
                assignedListMarker = true;
                continue;
            }

            const tag = group.element.tagName.toUpperCase();
            if (!assignedListMarker && tag === "P") {
                const runs = await extractInlineChildren(group.element, context, { preserveWhitespace: false });
                paragraphs.push(makeListParagraph(docxLib, runs, ordered, depth, context));
                assignedListMarker = true;
                continue;
            }

            if (!assignedListMarker) {
                paragraphs.push(makeListParagraph(docxLib, [new docxLib.TextRun("")], ordered, depth, context));
                assignedListMarker = true;
            }

            paragraphs.push(...(await convertBlockElement(group.element, context)));
        }

        if (!assignedListMarker) {
            paragraphs.push(makeListParagraph(docxLib, [new docxLib.TextRun("")], ordered, depth, context));
        }

        for (const nested of nestedLists) {
            const nestedOrdered = nested.tagName.toUpperCase() === "OL";
            paragraphs.push(...(await convertList(nested, nestedOrdered, depth + 1, context)));
        }
    }

    return paragraphs;
}

async function convertTable(tableElement, context) {
    const docxLib = context.docxLib;
    const rowElements = [];

    for (const child of Array.from(tableElement.children)) {
        const tag = child.tagName.toUpperCase();
        if (tag === "THEAD" || tag === "TBODY" || tag === "TFOOT") {
            rowElements.push(...Array.from(child.children).filter((row) => row.tagName.toUpperCase() === "TR"));
        } else if (tag === "TR") {
            rowElements.push(child);
        }
    }

    const rows = [];
    for (const rowElement of rowElements) {
        const cells = [];
        for (const cellElement of Array.from(rowElement.children)) {
            const cellTag = cellElement.tagName.toUpperCase();
            if (cellTag !== "TH" && cellTag !== "TD") continue;
            const isHeader = cellTag === "TH";
            const cellChildren = await convertTableCellChildren(cellElement, context);
            cells.push(new docxLib.TableCell({
                shading: isHeader ? { type: docxLib.ShadingType.CLEAR, fill: "EEF4FF", color: "auto" } : undefined,
                children: cellChildren.length ? cellChildren : [new docxLib.Paragraph("")]
            }));
        }
        rows.push(new docxLib.TableRow({ children: cells }));
    }

    return new docxLib.Table({
        width: { size: 100, type: docxLib.WidthType.PERCENTAGE },
        rows
    });
}

async function convertTableCellChildren(cellElement, context) {
    const groupedContent = groupContentNodes(Array.from(cellElement.childNodes));
    if (groupedContent.length) {
        const children = [];
        for (const group of groupedContent) {
            if (group.type === "inline") {
                if (!inlineNodesHaveVisibleContent(group.nodes)) {
                    continue;
                }
                const runs = await extractInlineChildrenFromNodes(group.nodes, context, { preserveWhitespace: false });
                if (runs.length) {
                    children.push(makeParagraph(context.docxLib, runs, paragraphStyleForContext(context)));
                }
                continue;
            }
            children.push(...(await convertBlockElement(group.element, context)));
        }
        if (children.length) {
            return children;
        }
    }

    return [await convertParagraph(cellElement, context)];
}

async function convertStandaloneImage(element, context) {
    const imageRun = await imageElementToRun(element, context);
    return new context.docxLib.Paragraph({
        children: imageRun
            ? [imageRun]
            : [new context.docxLib.TextRun({ text: "[Image omitted]", italics: true, color: "B91C1C" })],
        alignment: context.docxLib.AlignmentType.CENTER,
        spacing: { before: 120, after: 160 }
    });
}

async function extractInlineChildren(element, context, inlineContext) {
    return extractInlineChildrenFromNodes(Array.from(element.childNodes), context, inlineContext);
}

async function extractInlineChildrenFromNodes(nodes, context, inlineContext) {
    const docxLib = context.docxLib;
    const output = [];

    for (const node of nodes) {
        if (node.nodeType === Node.TEXT_NODE) {
            const text = normalizeText(node.textContent || "", !!inlineContext.preserveWhitespace);
            if (text) {
                output.push(new docxLib.TextRun(buildRunOptions(text, inlineContext)));
            }
            continue;
        }
        if (node.nodeType !== Node.ELEMENT_NODE) continue;

        const element = node;
        const tag = element.tagName.toUpperCase();
        if (tag === "BR") {
            output.push(new docxLib.TextRun({ break: 1, text: "" }));
            continue;
        }
        if (tag === "IMG") {
            const imageRun = await imageElementToRun(element, context);
            if (imageRun) output.push(imageRun);
            continue;
        }
        if (tag === "INPUT" && (element.getAttribute("type") || "").toLowerCase() === "checkbox") {
            output.push(new docxLib.TextRun(buildRunOptions(element.checked ? "\u2611 " : "\u2610 ", inlineContext)));
            continue;
        }

        const nextInlineContext = deriveInlineContext(element, inlineContext);
        const children = await extractInlineChildren(element, context, nextInlineContext);

        if (tag === "A") {
            const link = element.getAttribute("href") || "";
            if (link && children.length) {
                output.push(new docxLib.ExternalHyperlink({ link, children }));
                continue;
            }
        }

        output.push(...children);
    }

    return output;
}

function deriveInlineContext(element, inlineContext) {
    const tag = element.tagName.toUpperCase();
    const nextContext = { ...inlineContext };

    if (tag === "STRONG" || tag === "B") nextContext.bold = true;
    if (tag === "EM" || tag === "I") nextContext.italics = true;
    if (tag === "DEL" || tag === "S") nextContext.strike = true;
    if (tag === "CODE") {
        nextContext.code = true;
        nextContext.font = DOCX_CODE_FONT;
    }

    const classes = Array.from(element.classList || []);
    if (classes.includes("token")) {
        const tokenClass = classes.find((className) => getDocxTokenStyle(className));
        if (tokenClass) {
            const tokenStyle = getDocxTokenStyle(tokenClass);
            if (tokenStyle?.color) {
                nextContext.color = tokenStyle.color;
            }
            if (tokenStyle?.bold) {
                nextContext.bold = true;
            }
            if (tokenStyle?.italics) {
                nextContext.italics = true;
            }
        }
        nextContext.code = true;
        nextContext.font = DOCX_CODE_FONT;
    }

    return nextContext;
}

function buildRunOptions(text, inlineContext) {
    const options = { text };
    if (inlineContext.bold) options.bold = true;
    if (inlineContext.italics) options.italics = true;
    if (inlineContext.strike) options.strike = true;
    if (inlineContext.color) options.color = inlineContext.color;
    if (inlineContext.code) {
        options.font = inlineContext.font || DOCX_CODE_FONT;
        options.size = 18;
        options.shading = {
            type: "clear",
            fill: "F1F5F9",
            color: "auto"
        };
    }
    return options;
}

function extractCodeLines(nodes, codeContext = {}) {
    const lines = [[]];

    const appendText = (text, context) => {
        if (!text) return;
        const parts = text.replace(/\r/g, "").split("\n");
        parts.forEach((part, index) => {
            if (part) {
                pushCodeFragment(lines[lines.length - 1], {
                    text: part,
                    bold: !!context.bold,
                    italics: !!context.italics,
                    color: context.color || "E5EEFB"
                });
            }
            if (index < parts.length - 1) {
                lines.push([]);
            }
        });
    };

    nodes.forEach((node) => {
        if (node.nodeType === Node.TEXT_NODE) {
            appendText(node.textContent || "", codeContext);
            return;
        }
        if (node.nodeType !== Node.ELEMENT_NODE) return;

        const element = node;
        const tag = element.tagName.toUpperCase();
        if (tag === "BR") {
            lines.push([]);
            return;
        }

        const nextContext = deriveCodeContext(element, codeContext);
        const childLines = extractCodeLines(Array.from(element.childNodes), nextContext);
        childLines.forEach((childLine, index) => {
            childLine.forEach((fragment) => pushCodeFragment(lines[lines.length - 1], fragment));
            if (index < childLines.length - 1) {
                lines.push([]);
            }
        });
    });

    return lines;
}

function deriveCodeContext(element, codeContext) {
    const nextContext = { ...codeContext };
    const tag = element.tagName.toUpperCase();
    if (tag === "STRONG" || tag === "B") nextContext.bold = true;
    if (tag === "EM" || tag === "I") nextContext.italics = true;

    Array.from(element.classList || []).forEach((className) => {
        const tokenStyle = getDocxTokenStyle(className);
        if (tokenStyle?.color) {
            nextContext.color = tokenStyle.color;
        }
        if (tokenStyle?.bold) {
            nextContext.bold = true;
        }
        if (tokenStyle?.italics) {
            nextContext.italics = true;
        }
    });

    return nextContext;
}

function pushCodeFragment(line, fragment) {
    if (!fragment.text) return;
    const previous = line[line.length - 1];
    if (
        previous
        && previous.bold === fragment.bold
        && previous.italics === fragment.italics
        && previous.color === fragment.color
    ) {
        previous.text += fragment.text;
        return;
    }
    line.push({ ...fragment });
}

function trimTrailingBlankCodeLines(lines) {
    const trimmed = lines.map((line) => line.slice());
    while (trimmed.length > 1 && isBlankCodeLine(trimmed[trimmed.length - 1])) {
        trimmed.pop();
    }
    return trimmed;
}

function isBlankCodeLine(line) {
    if (!line.length) return true;
    return line.every((fragment) => !String(fragment.text || "").trim());
}

function buildCodeLineRuns(docxLib, line) {
    if (!line.length) {
        return [new docxLib.TextRun({
            text: " ",
            font: DOCX_CODE_FONT,
            size: 18,
            color: "E5EEFB"
        })];
    }

    return line.map((fragment) => new docxLib.TextRun({
        text: fragment.text,
        font: DOCX_CODE_FONT,
        size: 18,
        color: fragment.color || "E5EEFB",
        bold: !!fragment.bold,
        italics: !!fragment.italics
    }));
}

function paragraphStyleForContext(context) {
    const style = {
        spacing: { after: 180 },
        alignment: context.docxLib.AlignmentType.LEFT
    };

    if (context.inBlockquote) {
        style.indent = { left: 520 };
        style.border = {
            left: { color: "3B82F6", space: 1, size: 8, style: context.docxLib.BorderStyle.SINGLE }
        };
        style.shading = { type: context.docxLib.ShadingType.CLEAR, fill: "F8FAFC", color: "auto" };
    }

    return style;
}

function makeParagraph(docxLib, children, props = {}) {
    return new docxLib.Paragraph({
        children,
        ...props
    });
}

function makeListParagraph(docxLib, runs, ordered, depth, context) {
    const listParagraphStyle = paragraphStyleForContext(context);
    listParagraphStyle.spacing = { after: 60 };
    return new docxLib.Paragraph({
        children: runs.length ? runs : [new docxLib.TextRun("")],
        ...(ordered
            ? { numbering: { reference: "markdown-exporter-ordered", level: depth } }
            : { bullet: { level: depth } }),
        ...listParagraphStyle
    });
}

function normalizeText(text, preserveWhitespace) {
    if (!text) return "";
    if (preserveWhitespace) return text.replace(/\r/g, "");
    return text.replace(/\s+/g, " ");
}

function isBlockLevelElement(node) {
    if (!node || node.nodeType !== Node.ELEMENT_NODE) {
        return false;
    }

    const tag = node.tagName.toUpperCase();
    return BLOCK_CONTAINER_TAGS.has(tag)
        || LIST_TAGS.has(tag)
        || tag === "P"
        || tag === "BLOCKQUOTE"
        || tag === "PRE"
        || tag === "TABLE"
        || tag === "HR"
        || tag === "IMG"
        || /^H[1-6]$/.test(tag);
}

function isListElement(node) {
    return !!node
        && node.nodeType === Node.ELEMENT_NODE
        && LIST_TAGS.has(node.tagName.toUpperCase());
}

function groupContentNodes(nodes) {
    const groups = [];
    let inlineNodes = [];

    const flushInline = () => {
        if (!inlineNodes.length) return;
        groups.push({ type: "inline", nodes: inlineNodes });
        inlineNodes = [];
    };

    for (const node of nodes) {
        if (isBlockLevelElement(node)) {
            flushInline();
            groups.push({ type: "block", element: node });
            continue;
        }
        if (node.nodeType === Node.TEXT_NODE || node.nodeType === Node.ELEMENT_NODE) {
            inlineNodes.push(node);
        }
    }

    flushInline();
    return groups;
}

function inlineNodesHaveVisibleContent(nodes) {
    for (const node of nodes) {
        if (node.nodeType === Node.TEXT_NODE) {
            if ((node.textContent || "").trim()) {
                return true;
            }
            continue;
        }

        if (node.nodeType !== Node.ELEMENT_NODE) {
            continue;
        }

        const element = node;
        const tag = element.tagName.toUpperCase();
        if (tag === "BR") {
            return true;
        }
        if (tag === "IMG") {
            return true;
        }
        if (tag === "INPUT" && (element.getAttribute("type") || "").toLowerCase() === "checkbox") {
            return true;
        }
        if ((element.textContent || "").trim()) {
            return true;
        }
    }
    return false;
}

async function imageElementToRun(element, context) {
    const src = element.getAttribute("src") || "";
    if (!src) return null;

    try {
        const { data, type, width, height } = await loadImageForDocx(src, element);
        return new context.docxLib.ImageRun({
            data,
            type,
            transformation: scaleImage(width, height, 560, 720)
        });
    } catch (error) {
        context.warnings.push(`Image could not be embedded in DOCX: ${src}`);
        return null;
    }
}

async function loadImageForDocx(src, element) {
    const blob = src.startsWith("data:")
        ? dataUrlToBlob(src)
        : await fetchImageBlob(src);
    const data = await blob.arrayBuffer();
    const type = mimeToDocxType(blob.type || guessMimeTypeFromSrc(src));
    const dimensions = await readImageDimensions(src, blob, element);
    return { data, type, width: dimensions.width, height: dimensions.height };
}

async function fetchImageBlob(src) {
    const response = await fetch(src, { mode: "cors" });
    if (!response.ok) {
        throw new Error(`Image fetch failed: ${response.status}`);
    }
    return response.blob();
}

function dataUrlToBlob(dataUrl) {
    const parts = dataUrl.split(",");
    const meta = parts[0] || "";
    const mime = /data:([^;]+)/.exec(meta)?.[1] || "image/png";
    const binary = atob(parts[1] || "");
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i += 1) {
        bytes[i] = binary.charCodeAt(i);
    }
    return new Blob([bytes], { type: mime });
}

function mimeToDocxType(mime) {
    if (/png/i.test(mime)) return "png";
    if (/jpe?g/i.test(mime)) return "jpg";
    if (/gif/i.test(mime)) return "gif";
    if (/bmp/i.test(mime)) return "bmp";
    if (/svg/i.test(mime)) return "svg";
    return "png";
}

function guessMimeTypeFromSrc(src) {
    if (/\.png($|\?)/i.test(src)) return "image/png";
    if (/\.jpe?g($|\?)/i.test(src)) return "image/jpeg";
    if (/\.gif($|\?)/i.test(src)) return "image/gif";
    if (/\.bmp($|\?)/i.test(src)) return "image/bmp";
    if (/\.svg($|\?)/i.test(src)) return "image/svg+xml";
    return "image/png";
}

async function readImageDimensions(src, blob, element) {
    const explicitWidth = Number(element.getAttribute("width")) || 0;
    const explicitHeight = Number(element.getAttribute("height")) || 0;
    if (explicitWidth > 0 && explicitHeight > 0) {
        return { width: explicitWidth, height: explicitHeight };
    }

    const objectUrl = src.startsWith("data:") ? src : URL.createObjectURL(blob);
    try {
        return await new Promise((resolve, reject) => {
            const image = new Image();
            image.onload = () => resolve({
                width: image.naturalWidth || image.width || 400,
                height: image.naturalHeight || image.height || 240
            });
            image.onerror = () => reject(new Error("Could not read image dimensions."));
            image.src = objectUrl;
        });
    } finally {
        if (!src.startsWith("data:")) {
            URL.revokeObjectURL(objectUrl);
        }
    }
}

function scaleImage(width, height, maxWidth, maxHeight) {
    if (!width || !height) {
        return { width: maxWidth, height: Math.round(maxWidth * 0.62) };
    }
    const scale = Math.min(1, maxWidth / width, maxHeight / height);
    return {
        width: Math.max(1, Math.round(width * scale)),
        height: Math.max(1, Math.round(height * scale))
    };
}
