import { getPrismTokenStyle } from "./token-styles.js";

const BLOCK_CONTAINER_TAGS = new Set(["DIV", "SECTION", "ARTICLE", "FIGURE"]);
const LIST_TAGS = new Set(["UL", "OL"]);

export function buildPdfDefinition(exportRoot, options = {}) {
    const pageSize = options.pageSize === "a4" ? "A4" : "LETTER";
    const pageOrientation = options.orientation === "landscape" ? "landscape" : "portrait";
    const marginPt = inchesToPt(options.marginIn || 0.5);

    return {
        version: "1.7",
        tagged: true,
        displayTitle: true,
        language: "en-US",
        info: {
            title: options.title || options.filename || "Markdown Export",
            author: "Jesse Anderson",
            subject: "Generated by Tools Hub Markdown Exporter"
        },
        pageSize,
        pageOrientation,
        pageMargins: [marginPt, marginPt, marginPt, marginPt],
        defaultStyle: {
            font: "SourceSerifPro",
            fontSize: 11.5,
            lineHeight: 1.5,
            color: "#111827"
        },
        content: convertBlockNodes(Array.from(exportRoot.childNodes), { topLevel: true }),
        styles: {
            h1: { font: "SourceSerifPro", fontSize: 22, bold: true, color: "#0f172a", margin: [0, 0, 0, 8] },
            h2: { font: "SourceSerifPro", fontSize: 17, bold: true, color: "#0f172a", margin: [0, 6, 0, 6] },
            h3: { font: "SourceSerifPro", fontSize: 13.5, bold: true, color: "#1e3a8a", margin: [0, 4, 0, 6] },
            h4: { font: "SourceSerifPro", fontSize: 12, bold: true, color: "#0f172a", margin: [0, 4, 0, 4] },
            h5: { font: "SourceSerifPro", fontSize: 11, bold: true, color: "#334155", margin: [0, 4, 0, 4] },
            h6: { font: "SourceSerifPro", fontSize: 10.5, bold: true, color: "#334155", margin: [0, 4, 0, 4] },
            lead: { fontSize: 12.5, color: "#475467", lineHeight: 1.55 },
            paragraph: { margin: [0, 0, 0, 12] },
            inlineCode: { font: "SourceCodePro", fontSize: 9.9, color: "#0f172a", background: "#f1f5f9" },
            codeBlockText: { font: "SourceCodePro", fontSize: 9.2, color: "#0f172a", lineHeight: 1.3 },
            tableHeader: { font: "SourceSerifPro", bold: true, color: "#0f172a", fontSize: 9.2 },
            caption: { font: "SourceSerifPro", color: "#475467", fontSize: 10.2, italics: true }
        }
    };
}

function convertBlockNodes(nodes, context = {}) {
    const output = [];
    const grouped = groupContentNodes(nodes);

    grouped.forEach((group) => {
        if (group.type === "inline") {
            const paragraph = buildParagraphFromNodes(group.nodes, context, "paragraph");
            if (paragraph) {
                output.push(paragraph);
            }
            return;
        }
        const converted = convertBlockElement(group.element, context);
        if (Array.isArray(converted)) {
            output.push(...converted);
        } else if (converted) {
            output.push(converted);
        }
    });

    return output;
}

function convertBlockElement(element, context) {
    const tag = element.tagName.toUpperCase();
    switch (tag) {
        case "H1":
        case "H2":
        case "H3":
        case "H4":
        case "H5":
        case "H6":
            return convertHeading(element, tag);
        case "P":
            return convertParagraph(element, context);
        case "BLOCKQUOTE":
            return convertBlockquote(element);
        case "PRE":
            return convertCodeBlock(element);
        case "UL":
            return convertList(element, false);
        case "OL":
            return convertList(element, true);
        case "TABLE":
            return convertTable(element);
        case "HR":
            return {
                margin: [0, 8, 0, 18],
                canvas: [{
                    type: "line",
                    x1: 0,
                    y1: 0,
                    x2: 480,
                    y2: 0,
                    lineWidth: 1,
                    lineColor: "#cbd5e1"
                }]
            };
        case "IMG":
            return convertImage(element);
        default:
            if (BLOCK_CONTAINER_TAGS.has(tag)) {
                return convertBlockNodes(Array.from(element.childNodes), context);
            }
            return convertParagraph(element, context);
    }
}

function convertHeading(element, tag) {
    const styleMap = {
        H1: "h1",
        H2: "h2",
        H3: "h3",
        H4: "h4",
        H5: "h5",
        H6: "h6"
    };

    return {
        text: materializeTextPayload(extractInlineTextFragments(Array.from(element.childNodes))),
        style: styleMap[tag]
    };
}

function convertParagraph(element, context = {}) {
    const text = materializeTextPayload(extractInlineTextFragments(Array.from(element.childNodes)));
    if (!hasTextPayload(text)) {
        return null;
    }

    const paragraph = {
        text,
        style: "paragraph"
    };

    if (context.topLevel && isLeadParagraphCandidate(element)) {
        paragraph.style = ["paragraph", "lead"];
    }

    return paragraph;
}

function convertBlockquote(element) {
    const body = convertBlockNodes(Array.from(element.childNodes));
    if (!body.length) {
        return null;
    }

    return {
        stack: body,
        margin: [14, 0, 0, 12],
        color: "#334155"
    };
}

function convertCodeBlock(element) {
    const codeElement = element.querySelector("code") || element;
    const codeText = materializeTextPayload(extractCodeTextFragments(Array.from(codeElement.childNodes)));
    return {
        table: {
            widths: ["*"],
            body: [[{
                text: codeText,
                style: "codeBlockText",
                color: "#e5eefb",
                preserveLeadingSpaces: true
            }]]
        },
        layout: {
            fillColor: () => "#0b1220",
            hLineWidth: () => 1,
            vLineWidth: () => 1,
            hLineColor: () => "#1e293b",
            vLineColor: () => "#1e293b",
            paddingLeft: () => 12,
            paddingRight: () => 12,
            paddingTop: () => 10,
            paddingBottom: () => 10
        },
        margin: [0, 0, 0, 14]
    };
}

function convertList(listElement, ordered) {
    const items = [];

    Array.from(listElement.children).forEach((item) => {
        if (item.tagName.toUpperCase() !== "LI") return;
        items.push(convertListItem(item));
    });

    if (!items.length) {
        return null;
    }

    return {
        margin: [0, 0, 0, 12],
        [ordered ? "ol" : "ul"]: items
    };
}

function convertListItem(itemElement) {
    const nestedLists = [];
    const contentNodes = [];

    Array.from(itemElement.childNodes).forEach((node) => {
        if (isListElement(node)) {
            nestedLists.push(node);
        } else {
            contentNodes.push(node);
        }
    });

    const stack = convertBlockNodes(contentNodes);
    nestedLists.forEach((nested) => {
        stack.push(convertList(nested, nested.tagName.toUpperCase() === "OL"));
    });

    if (!stack.length) {
        return "";
    }

    if (stack.length === 1) {
        return simplifyListItemNode(stack[0]);
    }

    return { stack };
}

function convertTable(tableElement) {
    const rows = [];
    const rowElements = [];

    Array.from(tableElement.children).forEach((child) => {
        const tag = child.tagName.toUpperCase();
        if (tag === "THEAD" || tag === "TBODY" || tag === "TFOOT") {
            rowElements.push(...Array.from(child.children).filter((row) => row.tagName.toUpperCase() === "TR"));
        } else if (tag === "TR") {
            rowElements.push(child);
        }
    });

    let maxCols = 0;
    rowElements.forEach((rowElement) => {
        maxCols = Math.max(maxCols, rowElement.children.length);
        rows.push(Array.from(rowElement.children).map((cellElement) => convertTableCell(cellElement)));
    });

    if (!rows.length) {
        return null;
    }

    return {
        margin: [0, 0, 0, 14],
        table: {
            headerRows: rowElements.length ? 1 : 0,
            widths: new Array(Math.max(maxCols, 1)).fill("*"),
            body: rows
        },
        layout: {
            fillColor: (rowIndex) => (rowIndex === 0 ? "#eef4ff" : (rowIndex % 2 === 0 ? "#f8fafc" : null)),
            hLineColor: () => "#cbd5e1",
            vLineColor: () => "#cbd5e1",
            paddingLeft: () => 8,
            paddingRight: () => 8,
            paddingTop: () => 6,
            paddingBottom: () => 6
        }
    };
}

function convertTableCell(cellElement) {
    const content = convertBlockNodes(Array.from(cellElement.childNodes));
    const tag = cellElement.tagName.toUpperCase();

    if (!content.length) {
        return { text: "" };
    }

    if (content.length === 1 && tag === "TH" && isTextNode(content[0])) {
        return { ...content[0], style: ["tableHeader"] };
    }

    if (content.length === 1 && isTextNode(content[0])) {
        return content[0];
    }

    return {
        stack: content,
        ...(tag === "TH" ? { style: "tableHeader" } : {})
    };
}

function convertImage(element) {
    const src = element.getAttribute("src") || "";
    if (!src) return null;
    const width = Number(element.getAttribute("width")) || 0;
    const height = Number(element.getAttribute("height")) || 0;
    const imageNode = {
        image: src,
        margin: [0, 4, 0, 14],
        alignment: "center"
    };

    if (width > 0 && height > 0) {
        imageNode.fit = [Math.min(width, 440), Math.min(height, 520)];
    } else {
        imageNode.fit = [440, 520];
    }

    const alt = element.getAttribute("alt") || "";
    if (alt) {
        return {
            stack: [
                imageNode,
                { text: alt, style: "caption", alignment: "center", margin: [0, -6, 0, 10] }
            ]
        };
    }

    return imageNode;
}

function buildParagraphFromNodes(nodes, context = {}, style = "paragraph") {
    const text = materializeTextPayload(extractInlineTextFragments(nodes));
    if (!hasTextPayload(text)) {
        return null;
    }

    return {
        text,
        style
    };
}

function extractInlineTextFragments(nodes, inlineContext = {}) {
    const fragments = [];

    nodes.forEach((node) => {
        if (node.nodeType === Node.TEXT_NODE) {
            const text = normalizeInlineText(node.textContent || "");
            if (!text) return;
            fragments.push(applyInlineContext(text, inlineContext));
            return;
        }

        if (node.nodeType !== Node.ELEMENT_NODE) return;

        const element = node;
        const tag = element.tagName.toUpperCase();
        if (tag === "BR") {
            fragments.push({ text: "\n" });
            return;
        }

        if (tag === "IMG") {
            const alt = element.getAttribute("alt") || "[image]";
            fragments.push(applyInlineContext(alt, { ...inlineContext, italics: true, color: "#475467" }));
            return;
        }

        if (tag === "INPUT" && (element.getAttribute("type") || "").toLowerCase() === "checkbox") {
            fragments.push(applyInlineContext(element.checked ? "[x] " : "[ ] ", inlineContext));
            return;
        }

        const nextContext = deriveInlineContext(element, inlineContext);
        const children = extractInlineTextFragments(Array.from(element.childNodes), nextContext);
        fragments.push(...children);
    });

    return mergeAdjacentTextFragments(fragments);
}

function extractCodeTextFragments(nodes, codeContext = {}) {
    const fragments = [];

    nodes.forEach((node) => {
        if (node.nodeType === Node.TEXT_NODE) {
            const text = (node.textContent || "").replace(/\r/g, "");
            if (!text) return;
            fragments.push(applyCodeContext(text, codeContext));
            return;
        }

        if (node.nodeType !== Node.ELEMENT_NODE) return;

        const element = node;
        const tag = element.tagName.toUpperCase();
        if (tag === "BR") {
            fragments.push(applyCodeContext("\n", codeContext));
            return;
        }

        const nextContext = deriveCodeContext(element, codeContext);
        const children = extractCodeTextFragments(Array.from(element.childNodes), nextContext);
        fragments.push(...children);
    });

    return mergeAdjacentTextFragments(fragments);
}

function deriveInlineContext(element, inlineContext) {
    const tag = element.tagName.toUpperCase();
    const nextContext = { ...inlineContext };

    if (tag === "STRONG" || tag === "B") nextContext.bold = true;
    if (tag === "EM" || tag === "I") nextContext.italics = true;
    if (tag === "DEL" || tag === "S") nextContext.decoration = "lineThrough";
    if (tag === "A") {
        nextContext.link = element.getAttribute("href") || "";
        nextContext.color = "#1d4ed8";
        nextContext.decoration = "underline";
    }
    if (tag === "CODE") {
        nextContext.style = "inlineCode";
    }

    return nextContext;
}

function deriveCodeContext(element, codeContext) {
    const nextContext = { ...codeContext };
    const tag = element.tagName.toUpperCase();

    if (tag === "STRONG" || tag === "B") nextContext.bold = true;
    if (tag === "EM" || tag === "I") nextContext.italics = true;

    element.classList.forEach((className) => {
        const tokenStyle = getPrismTokenStyle(className);
        if (!tokenStyle) return;
        Object.assign(nextContext, tokenStyle);
    });

    return nextContext;
}

function applyInlineContext(text, inlineContext) {
    const hasStyle = !!(
        inlineContext.bold
        || inlineContext.italics
        || inlineContext.decoration
        || inlineContext.link
        || inlineContext.color
        || inlineContext.style
    );
    if (!hasStyle) {
        return text;
    }

    const fragment = { text };
    if (inlineContext.bold) fragment.bold = true;
    if (inlineContext.italics) fragment.italics = true;
    if (inlineContext.decoration) fragment.decoration = inlineContext.decoration;
    if (inlineContext.link) fragment.link = inlineContext.link;
    if (inlineContext.color) fragment.color = inlineContext.color;
    if (inlineContext.style) fragment.style = inlineContext.style;
    return fragment;
}

function applyCodeContext(text, codeContext) {
    const hasStyle = !!(
        codeContext.bold
        || codeContext.italics
        || codeContext.color
    );
    if (!hasStyle) {
        return text;
    }

    const fragment = { text };
    if (codeContext.bold) fragment.bold = true;
    if (codeContext.italics) fragment.italics = true;
    if (codeContext.color) fragment.color = codeContext.color;
    return fragment;
}

function mergeAdjacentTextFragments(fragments) {
    const output = [];

    fragments.forEach((fragment) => {
        if (typeof fragment === "string") {
            const previous = output[output.length - 1];
            if (typeof previous === "string") {
                output[output.length - 1] = previous + fragment;
            } else {
                output.push(fragment);
            }
            return;
        }

        const previous = output[output.length - 1];
        if (previous && typeof previous === "object" && sameInlineShape(previous, fragment)) {
            previous.text += fragment.text;
            return;
        }
        output.push(fragment);
    });

    return output;
}

function materializeTextPayload(fragments) {
    if (!fragments.length) {
        return "";
    }
    if (fragments.every((fragment) => typeof fragment === "string")) {
        return fragments.join("");
    }
    return fragments;
}

function hasTextPayload(payload) {
    if (!payload) return false;
    if (typeof payload === "string") return !!payload.trim();
    if (Array.isArray(payload)) return payload.length > 0;
    return typeof payload === "object" && typeof payload.text === "string" ? !!payload.text.trim() : true;
}

function simplifyListItemNode(node) {
    if (!node) return "";
    if (typeof node === "string") return node;
    if (isTextNode(node) && typeof node.text === "string") {
        return node.text;
    }
    return node;
}

function sameInlineShape(left, right) {
    return left.bold === right.bold
        && left.italics === right.italics
        && left.decoration === right.decoration
        && left.link === right.link
        && left.color === right.color
        && left.style === right.style;
}

function normalizeInlineText(text) {
    if (!text) return "";
    return text.replace(/\s+/g, " ");
}

function groupContentNodes(nodes) {
    const groups = [];
    let inlineNodes = [];

    const flushInline = () => {
        if (!inlineNodes.length) return;
        groups.push({ type: "inline", nodes: inlineNodes });
        inlineNodes = [];
    };

    nodes.forEach((node) => {
        if (isBlockLevelElement(node)) {
            flushInline();
            groups.push({ type: "block", element: node });
            return;
        }

        if (node.nodeType === Node.TEXT_NODE || node.nodeType === Node.ELEMENT_NODE) {
            inlineNodes.push(node);
        }
    });

    flushInline();
    return groups;
}

function isBlockLevelElement(node) {
    if (!node || node.nodeType !== Node.ELEMENT_NODE) {
        return false;
    }

    const tag = node.tagName.toUpperCase();
    return BLOCK_CONTAINER_TAGS.has(tag)
        || LIST_TAGS.has(tag)
        || tag === "P"
        || tag === "BLOCKQUOTE"
        || tag === "PRE"
        || tag === "TABLE"
        || tag === "HR"
        || tag === "IMG"
        || /^H[1-6]$/.test(tag);
}

function isListElement(node) {
    return !!node
        && node.nodeType === Node.ELEMENT_NODE
        && LIST_TAGS.has(node.tagName.toUpperCase());
}

function isLeadParagraphCandidate(element) {
    const previous = element.previousElementSibling;
    return !!previous && previous.tagName && previous.tagName.toUpperCase() === "H1";
}

function isTextNode(node) {
    return !!node && Object.prototype.hasOwnProperty.call(node, "text");
}

function inchesToPt(inches) {
    return Math.round(inches * 72);
}
